# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

pod "SwiftyJSON", ">= 2.1.3"

workspace 'combinedTest'


target 'combinedTest' do

end

target 'combinedTestTests' do

end

